name: .NET Linux Test

on:
  pull_request:
    branches: [ "**" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore dependencies
      run: dotnet restore Pmad.Cartography.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release Pmad.Cartography.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release Pmad.Cartography.sln